cmake_minimum_required(VERSION 3.8 FATAL_ERROR)
project(openfpm_vcluster LANGUAGES C CXX)

list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR}/cmake_modules/)

if (POLICY CMP0074)
  cmake_policy(SET CMP0074 NEW)
endif()

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CUDA_STANDARD 14)
if (CUDA_ON_BACKEND STREQUAL "METAL")
	set(CMAKE_CXX_STANDARD 17)
	set(CMAKE_CXX_STANDARD_REQUIRED ON)
endif()

if(MPI_FOUND)
	set(DEFINE_HAVE_MPI "#define HAVE_MPI")
else()
	message( FATAL_ERROR "MPI is required in order to install OpenFPM" )
endif()

if (ENABLE_VCLUSTER_GARBAGE_INJECTOR)
	set(DEFINE_VCLUSTER_GARBAGE_INJECTOR "#define VCLUSTER_GARBAGE_INJECTOR")
endif()

include_directories(SYSTEM ${MPI_INCLUDE_PATH})

add_subdirectory(src)

get_directory_property(hasParent PARENT_DIRECTORY)
if(hasParent)
	set(DEFINE_VCLUSTER_GARBAGE_INJECTOR ${DEFINE_VCLUSTER_GARBAGE_INJECTOR} CACHE INTERNAL "")
	set(DEFINE_HAVE_MPI ${DEFINE_HAVE_MPI} CACHE INTERNAL "")
endif()
